# Generated by Django 3.2.7 on 2021-09-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='uploads/audio/')),
                ('amplitude', models.ImageField(upload_to='uploads/amplitude')),
                ('spectogram', models.ImageField(upload_to='uploads/spectogram')),
                ('silence', models.ImageField(upload_to='uploads/silence')),
            ],
        ),
    ]
